# Generated by Django 4.1.13 on 2024-11-09 19:23

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('email_login', models.EmailField(max_length=100)),
                ('senha_login', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_representante', models.CharField(max_length=100)),
                ('cpf_representante', models.CharField(max_length=11)),
                ('telefone_representante', models.CharField(max_length=20)),
                ('email_representante', models.EmailField(max_length=100)),
                ('objetivo_ong', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
