# Generated by Django 4.1.13 on 2024-11-10 21:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoRecebida',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_empresa', models.CharField(max_length=256)),
                ('id_ong', models.CharField(max_length=256)),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.CharField(blank=True, max_length=256, null=True)),
                ('quantidade_produto', models.CharField(max_length=20)),
                ('unidade_medida_produto', models.CharField(max_length=50)),
                ('categoria_produto', models.CharField(max_length=50)),
                ('data_doado_produto', models.DateTimeField()),
                ('data_recebido_produto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
