# Generated by Django 4.1.13 on 2024-11-09 12:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_empresa', models.CharField(max_length=256)),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.CharField(blank=True, max_length=256, null=True)),
                ('quantidade_produto', models.CharField(max_length=20)),
                ('unidade_medida_produto', models.CharField(choices=[('gramas', 'Grama'), ('kg', 'Kg'), ('tonelada', 'Tonelada'), ('unidade', 'Unidade')], max_length=50)),
                ('categoria_produto', models.CharField(choices=[('carne', 'Carne'), ('flv', 'Frutas, legumes e verduras'), ('frios', 'Frios'), ('higiene', 'Higiene'), ('limpeza', 'Limpeza'), ('mercearia', 'Mercearia')], max_length=50)),
                ('data_doado_produto', models.DateTimeField(auto_now_add=True)),
                ('disponivel_produto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj_empresa', models.CharField(max_length=20)),
                ('tipo_empresa', models.CharField(max_length=100)),
                ('email_login_empresa', models.EmailField(max_length=100)),
                ('senha_login_empresa', models.CharField(max_length=100)),
                ('cep_empresa', models.CharField(max_length=20)),
                ('estado_empresa', models.CharField(max_length=100)),
                ('cidade_empresa', models.CharField(max_length=100)),
                ('bairro_empresa', models.CharField(max_length=100)),
                ('rua_empresa', models.CharField(max_length=100)),
                ('numero_empresa', models.CharField(max_length=10)),
                ('complemento_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_representante_empresa', models.CharField(max_length=100)),
                ('cpf_representante_empresa', models.CharField(max_length=11)),
                ('telefone_representante_empresa', models.CharField(max_length=20)),
                ('email_representante_empresa', models.EmailField(max_length=100)),
            ],
        ),
    ]
