# Generated by Django 4.1.13 on 2024-10-10 21:53

from django.db import migrations, models
import djongo.models.fields
import empresa.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.CharField(blank=True, max_length=256, null=True)),
                ('quantidade_produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj_empresa', models.CharField(max_length=14)),
                ('tipo_empresa', models.CharField(max_length=100)),
                ('email_login_empresa', models.EmailField(max_length=100)),
                ('senha_login_empresa', models.CharField(max_length=100)),
                ('cep_empresa', models.CharField(max_length=8)),
                ('estado_empresa', models.CharField(max_length=100)),
                ('cidade_empresa', models.CharField(max_length=100)),
                ('bairro_empresa', models.CharField(max_length=100)),
                ('rua_empresa', models.CharField(max_length=100)),
                ('numero_empresa', models.CharField(max_length=10)),
                ('complemento_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_representante_empresa', models.CharField(max_length=100)),
                ('cpf_representante_empresa', models.CharField(max_length=11)),
                ('telefone_representante_empresa', models.CharField(max_length=20)),
                ('email_representante_empresa', models.EmailField(max_length=100)),
                ('doacao_empresa', djongo.models.fields.ArrayField(blank=True, model_container=empresa.models.Doacao, null=True)),
                ('produto_ofertado_empresa', djongo.models.fields.ArrayField(blank=True, model_container=empresa.models.ProdutoOfertado, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoOfertado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.CharField(blank=True, max_length=256, null=True)),
                ('quantidade_produto', models.IntegerField()),
                ('validade_produto', models.DateTimeField()),
                ('disponivel_produto', models.BooleanField(default=True)),
            ],
        ),
    ]
