# Generated by Django 4.1.13 on 2024-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='bairro_empresa',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cep_empresa',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cidade_empresa',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cnpj_empresa',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='complemento_empresa',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cpf_representante_empresa',
            new_name='cpf_representante',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='email_login_empresa',
            new_name='email_login',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='email_representante_empresa',
            new_name='email_representante',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='estado_empresa',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_empresa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_representante_empresa',
            new_name='nome_representante',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='numero_empresa',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='rua_empresa',
            new_name='rua',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='senha_login_empresa',
            new_name='senha_login',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefone_representante_empresa',
            new_name='telefone_representante',
        ),
    ]
