# Generated by Django 4.1.13 on 2024-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep_empresa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_empresa',
            field=models.CharField(max_length=20),
        ),
    ]
