# Generated by Django 4.1.13 on 2024-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='disponivel_produto',
            field=models.BooleanField(default=True),
        ),
    ]
