# Generated by Django 4.1.13 on 2024-10-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_cep_empresa_alter_empresa_cnpj_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='doacao_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='produto_ofertado_empresa',
        ),
    ]
