# Generated by Django 4.1.13 on 2024-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_doacao_disponivel_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doado_produto',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
