# Generated by Django 4.1.13 on 2024-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_doacao_disponivel_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='disponivel_produto',
            field=models.BooleanField(default=True),
        ),
    ]
