# Generated by Django 4.1.13 on 2024-11-09 12:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('valor_doacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('cpf_pessoa', models.CharField(max_length=20)),
                ('email_login_pessoa', models.EmailField(max_length=100)),
                ('senha_login_pessoa', models.CharField(max_length=100)),
                ('data_nascimento_pessoa', models.DateField()),
                ('telefone_pessoa', models.CharField(max_length=20)),
            ],
        ),
    ]
