# Generated by Django 4.1.13 on 2024-10-21 00:05

from django.db import migrations, models
import djongo.models.fields
import pessoa.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_doacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('cpf_pessoa', models.CharField(max_length=20)),
                ('email_login_pessoa', models.CharField(max_length=100)),
                ('senha_login_pessoa', models.CharField(max_length=100)),
                ('data_nascimento_pessoa', models.DateField()),
                ('telefone_pessoa', models.CharField(max_length=20)),
                ('doacao_pessoa', djongo.models.fields.ArrayField(blank=True, model_container=pessoa.models.Doacao, null=True)),
            ],
        ),
    ]
