# Generated by Django 4.1.13 on 2024-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento_pessoa',
            field=models.DateField(),
        ),
    ]
