# Generated by Django 4.1.13 on 2024-10-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email_login_pessoa',
            field=models.EmailField(max_length=100),
        ),
    ]
