# Generated by Django 4.1.13 on 2024-11-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='valor_total_doado_pessoa',
            field=models.FloatField(default=0),
        ),
    ]
