# Generated by Django 4.1.13 on 2024-12-03 19:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0002_pessoa_valor_total_doado_pessoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="doacao",
            name="data_doado",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="id_pessoa",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 12, 3, 19, 41, 4, 127518, tzinfo=datetime.timezone.utc
                ),
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doacao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
