# Generated by Django 4.1.13 on 2024-10-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_pessoa_email_login_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='doacao_pessoa',
        ),
    ]
